name: CCMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, CoreProtect]
authors: [Madgeek1450, Prozza, Scuph, ImALuckyGuy]

# plugin.yml is no longer used to define commands.
